### ISSUE TITLE
[회고] 1주차 회고

### ISSUE THREAD

**Issue by NaMinhyeok** [Gachon-CS-Study/CS-Study#21]
# 1주차 회고 🔥

컴퓨터 구조로 1주차 스터디를 진행해보았는데 제가 진행하는데 있어서 부족한 부분이 많은 것 같습니다. 
그래도 다들 한주동안 열심히 공부하시고 발표준비해주시느라 고생많으셨습니다 ! 👍

더 나은 스터디를 진행하기 위해서 여러분들 의견을 들어보려고 합니다. 
혹시라도 앞으로 스터디가 어떻게 진행되었으면 좋을지 의견 있으시면 나눠주시면 감사하겠습니다 !
코멘트를 통해서 주제에 대한 것이든, 스터디에 대한 것이든, 그 밖에 다른 의견도 좋습니다 ! 그냥 **본인이 얘기하고싶은 것** 위주로 작성해주시면 되겠습니다 ! 😀

**Comment by seungwon7934** [comment]
다들 설명을 잘해주셔서 좋았습니다!

**Comment by ehs208** [comment]
기대이상으로 도움이 많이 됐던거 같습니다! 커피챗 같은 것도 잠깐 해서 조금 친밀감 형성하면서 스터디를 진행해도 좋을 것 같습니다.

**Comment by hyper-cloud10** [comment]
조사를 완벽히 하지는 못했지만, 다음 주에 조사를 마쳐 발전된 모습을 보여드리도록 하겠습니다.
